Parameters:
  DBNameP:
    Type: String
  MUser:
    Type: String
  MPass:
    Type: String
    Description: "It shouldn't be less than 8 characters"
  Resources:
    MyDBvideoInstance:
      Type: AWS::RDS::DBInstance
      Properties:
        DBName: !Ref DBNameP
        MasterUsername: !Ref MUser
        MasterUserPassword: !Ref MPass
        Engine: MySQL
        DBInstanceClass: db.t2.micro
        StorageType: gp2
        PubliclyAccessible: True
        AllocatedStorage: "20"
        DBInstanceIdentifier: !Join ["-", [ "MyDbInstance", !Ref "AWS::Region"]]
        AvailabilityZone: !Select [1, !GetAZs ""]